sudo: required
dist: xenial
language: go

services:
  - docker
  
script:
  - docker ps
  - docker build -t "staticwebserver:v1" .
  - docker run -d -P "staticwebserver:v1" /usr/sbin/apache2ctl -D FOREGROUND
 
after_script:
  - echo "Image built and run sucessfully"
