sudo: required
dist: xenial
language: go

services:
  - docker
  
script:
  - docker pull hello-world 
  - docker run -d hello-world
  - docker ps
  - docker build -t "staticwebserver:v1" .
  - docker run -d staticwebserver /usr/sbin/apache2ctl -D FOREGROUND
 
after_script:
  - echo "Image built and run sucessfully"
